#TODO 2) Specify environment's name and dependencies
name: project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - ipython
  - numpy
  - cudatoolkit
  - pytorch
  - torchvision
  - pip
  - pip:  # Installed packages not on conda through pip
    - -e .  # Install project package in development mode
    - -r tests/requirements.txt  # Install packages only for testing purpose
    - pytorch-lightning>=1.2.0
    - hydra-core --pre  # Using 1.1 pre-release for the moment
    - loguru
    - coloredlogs
    - pudb
